FROM openssl-profuzzbench

# Import environment variable to pass as parameter to make (e.g., to make parallel builds with -j)
ARG MAKE_OPT

# Set up fuzzers
RUN git clone https://github.com/profuzzbench/aflnet.git && \
    cd aflnet && \
    make clean all $MAKE_OPT && \
    cd llvm_mode && make $MAKE_OPT

ENV AFLNET="/home/ubuntu/aflnet"
ENV AFL_PATH=${AFLNET}
ENV PATH=${AFL_PATH}:${PATH}

# Download and compile OpenSSL for fuzzing
RUN cd ${WORKDIR} && \
    git clone https://github.com/openssl/openssl.git && \
    cd openssl && \
    cp ${WORKDIR}/*.pem ./ && \
    git checkout OpenSSL_1_1_1j && \
    patch -p1 < ${WORKDIR}/rand.patch && \
    CC=afl-clang-fast ./config no-shared --with-rand-seed=none && \
    CC=afl-clang-fast make $MAKE_OPT
#   FIXME AFL_USE_ASAN=1 CC=afl-clang-fast make $MAKE_OPT

COPY --chown=ubuntu:ubuntu in-tls ${WORKDIR}/in-tls
COPY --chown=ubuntu:ubuntu tls.dict ${WORKDIR}/tls.dict
