FROM openssl-profuzzbench

# Import environment variable to pass as parameter to make (e.g., to make parallel builds with -j)
ARG MAKE_OPT

# Set up StateAFL
ENV STATEAFL="/home/ubuntu/stateafl"
ENV STATEAFL_CFLAGS=""

RUN git clone https://github.com/tlspuffin/stateafl.git $STATEAFL && \
    cd $STATEAFL && \
    make clean all $MAKE_OPT && \
    rm as && \
    cd llvm_mode && CFLAGS="${STATEAFL_CFLAGS}" make $MAKE_OPT

# Set up environment variables for StateAFL
ENV AFL_PATH=${STATEAFL}
ENV PATH=${STATEAFL}:${PATH}

# Dedicated instrumented version for StateAFL
RUN cd ${WORKDIR} && \
    git clone https://github.com/openssl/openssl.git openssl-stateafl && \
    cd openssl-stateafl && \
    cp ${WORKDIR}/*.pem ./ && \
    git checkout OpenSSL_1_1_1j && \
    patch -p1 < ${WORKDIR}/rand.patch && \
    CC=${STATEAFL}/afl-clang-fast ./config no-shared --with-rand-seed=none && \
    CC=${STATEAFL}/afl-clang-fast make $MAKE_OPT

COPY --chown=ubuntu:ubuntu in-tls-replay ${WORKDIR}/in-tls-replay
COPY --chown=ubuntu:ubuntu run-stateafl.sh ${WORKDIR}/run-stateafl

# For deterministic timestamps
#RUN cd ${WORKDIR} && \
#    git clone https://github.com/stateafl/libfaketime-asan-fixed libfaketime-asan-fixed && \
#    cd libfaketime-asan-fixed && \
#    git checkout 7e46ea4 && \
#    cd src && \
#    make
#ENV LD_PRELOAD=$WORKDIR/libfaketime-asan-fixed/src/libfaketime.so.1
#ENV FAKETIME="2000-01-01 11:12:13"
#ENV FAKETIME_ONLY_CMDS="openssl"
