FROM openssl

# Import environment variable to pass as parameter to make (e.g., to make parallel builds with -j)
ARG MAKE_OPT

# Dedicated instrumented version for StateAFL
ENV STATEAFL="/home/ubuntu/stateafl"
ENV AFL_PATH=${STATEAFL}
ENV STATEAFL_CFLAGS=""

ARG PAT_STATEAFL
RUN git clone https://github.com/stateafl/stateafl.git $STATEAFL && \
    cd $STATEAFL && \
    make clean all $MAKE_OPT && \
    cd llvm_mode && CFLAGS="${STATEAFL_CFLAGS}" make $MAKE_OPT

RUN cd ${WORKDIR} && \
    git clone https://github.com/openssl/openssl.git openssl-stateafl && \
    cd openssl-stateafl && \
    cp ${WORKDIR}/*.pem ./ && \
    git checkout 0437435a && \
    patch -p1 < ${WORKDIR}/rand.patch && \
    CC=${STATEAFL}/afl-clang-fast ./config no-shared --with-rand-seed=none && \
    CC=${STATEAFL}/afl-clang-fast make include/openssl/configuration.h include/openssl/opensslv.h include/crypto/bn_conf.h include/crypto/dso_conf.h && \
    CC=${STATEAFL}/afl-clang-fast make apps/openssl $MAKE_OPT

COPY --chown=ubuntu:ubuntu run-stateafl.sh ${WORKDIR}/run-stateafl

