FROM proftpd

# Use ubuntu as default username
USER ubuntu
WORKDIR /home/ubuntu

# Import environment variable to pass as parameter to make (e.g., to make parallel builds with -j)
ARG MAKE_OPT

# Set up StateAFL
ENV STATEAFL="/home/ubuntu/stateafl"
ENV STATEAFL_CFLAGS="-DENABLE_TRACE_GLOBAL_DATA -DBLACKLIST_ALLOC_SITES -DBLACKLIST_GLOBALS"

RUN git clone https://github.com/stateafl/stateafl.git $STATEAFL && \
    cd $STATEAFL && \
    make clean all $MAKE_OPT && \
    rm as && \
    cd llvm_mode && CFLAGS="${STATEAFL_CFLAGS}" make $MAKE_OPT

COPY --chown=ubuntu:ubuntu malloc.patch ${WORKDIR}/malloc.patch

# Set up environment variables for StateAFL
ENV AFL_PATH=${STATEAFL}
ENV PATH=${STATEAFL}:${PATH}

# Dedicated instrumented version for StateAFL
RUN cd ${WORKDIR} && \
    git clone https://github.com/proftpd/proftpd.git proftpd-stateafl && \
    cd proftpd-stateafl && \
    git checkout 4017eff8 && \
    patch -p1 < ${WORKDIR}/malloc.patch && \
    CC=${STATEAFL}/afl-clang-fast CXX=${STATEAFL}/afl-clang-fast++ ./configure --enable-devel=nodaemon:nofork && \
    make $MAKE_OPT

COPY --chown=ubuntu:ubuntu in-ftp-replay ${WORKDIR}/in-ftp-replay
COPY --chown=ubuntu:ubuntu run-stateafl.sh ${WORKDIR}/run-stateafl
COPY --chown=ubuntu:ubuntu blacklist.sh ${WORKDIR}/blacklist.sh

# The server runs in "/home/ubuntu" if login succeeds,
# otherwise, the CWD is $TARGETDIR. Create a link to share the same files for MVP tree.
RUN touch /home/ubuntu/.tree.mvp && \
    chmod ugo+rw /home/ubuntu/.tree.mvp && \
    ln /home/ubuntu/.tree.mvp ${WORKDIR}/proftpd-stateafl/.tree.mvp

RUN touch /home/ubuntu/.tree.count.mvp && \
    chmod ugo+rw /home/ubuntu/.tree.count.mvp && \
    ln /home/ubuntu/.tree.count.mvp ${WORKDIR}/proftpd-stateafl/.tree.count.mvp

# Switch default user to root
USER root
WORKDIR /home/ubuntu

# For deterministic timestamps
RUN cd ${WORKDIR} && \
    git clone https://github.com/stateafl/libfaketime-asan-fixed libfaketime-asan-fixed && \
    cd libfaketime-asan-fixed && \
    git checkout 7e46ea4 && \
    cd src && \
    make

ENV LD_PRELOAD=$WORKDIR/libfaketime-asan-fixed/src/libfaketime.so.1
ENV FAKETIME="2000-01-01 11:12:13"
ENV FAKETIME_ONLY_CMDS="proftpd"
