FROM proftpd

# Use ubuntu as default username
USER ubuntu
WORKDIR /home/ubuntu

# Import environment variable to pass as parameter to make (e.g., to make parallel builds with -j)
ARG MAKE_OPT

# Set up StateAFL
ENV STATEAFL="/home/ubuntu/stateafl"
ENV STATEAFL_CFLAGS="-DENABLE_TRACE_GLOBAL_DATA -DBLACKLIST_ALLOC_SITES -DBLACKLIST_GLOBALS"

RUN git clone https://github.com/stateafl/stateafl.git $STATEAFL && \
    cd $STATEAFL && \
    make clean all $MAKE_OPT && \
    cd llvm_mode && CFLAGS="${STATEAFL_CFLAGS}" make $MAKE_OPT

COPY --chown=ubuntu:ubuntu malloc.patch ${WORKDIR}/malloc.patch

# Set up environment variables for ASAN
env ASAN_OPTIONS='abort_on_error=1:symbolize=0:detect_leaks=0:detect_stack_use_after_return=1:detect_container_overflow=0:poison_array_cookie=0:malloc_fill_byte=0:max_malloc_fill_size=16777216'

# Set up environment variables for StateAFL
ENV AFL_PATH=${STATEAFL}
ENV PATH=${STATEAFL}:${PATH}

# Dedicated instrumented version for StateAFL
RUN cd ${WORKDIR} && \
    git clone https://github.com/proftpd/proftpd.git proftpd-stateafl && \
    cd proftpd-stateafl && \
    git checkout 4017eff8 && \
    patch -p1 < ${WORKDIR}/malloc.patch && \
    CC=${STATEAFL}/afl-clang-fast CXX=${STATEAFL}/afl-clang-fast++ ./configure --enable-devel=nodaemon:nofork && \
    make $MAKE_OPT

COPY --chown=ubuntu:ubuntu run-stateafl.sh ${WORKDIR}/run-stateafl
COPY --chown=ubuntu:ubuntu blacklist.sh ${WORKDIR}/blacklist.sh

# The server runs in "/home/ubuntu" if login succeeds,
# otherwise, the CWD is $TARGETDIR. Create a symlink to share the same files for MVP tree.
RUN touch /home/ubuntu/.tree.mvp && \
    chmod ugo+rw /home/ubuntu/.tree.mvp && \
    ln /home/ubuntu/.tree.mvp ${WORKDIR}/proftpd-stateafl/.tree.mvp

RUN touch /home/ubuntu/.tree.count.mvp && \
    chmod ugo+rw /home/ubuntu/.tree.count.mvp && \
    ln -s /home/ubuntu/.tree.count.mvp ${WORKDIR}/proftpd-stateafl/.tree.count.mvp

# Switch default user to root
USER root
WORKDIR /home/ubuntu

# For deterministic timestamps
RUN apt -y install libfaketime

ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1
ENV FAKETIME="2000-01-01 11:12:13"
ENV FAKETIME_ONLY_CMDS="proftpd"
