FROM dnsmasq

# Import environment variable to pass as parameter to make (e.g., to make parallel builds with -j)
ARG MAKE_OPT

# Dedicated instrumented version for StateAFL
ENV STATEAFL="/home/ubuntu/stateafl"
ENV AFL_PATH=${STATEAFL}

ARG PAT_STATEAFL
RUN git clone https://github.com/stateafl/stateafl.git $STATEAFL && \
    cd $STATEAFL && \
    make clean all $MAKE_OPT && \
    cd llvm_mode && make $MAKE_OPT

RUN cd $WORKDIR && \
    git clone git://thekelleys.org.uk/dnsmasq.git dnsmasq-stateafl && \
    cd dnsmasq-stateafl && \
    git checkout v2.73rc6 && \
    patch -p1 < ${WORKDIR}/dnsmasq.patch && \
    CC=${STATEAFL}/afl-clang-fast make $MAKE_OPT

COPY --chown=ubuntu:ubuntu run-stateafl.sh ${WORKDIR}/run-stateafl

