FROM dcmtk

# Import environment variable to pass as parameter to make (e.g., to make parallel builds with -j)
ARG MAKE_OPT

# Dedicated instrumented version for StateAFL
ENV STATEAFL="/home/ubuntu/stateafl"

RUN git clone https://github.com/stateafl/stateafl.git $STATEAFL && \
    cd $STATEAFL && \
    make clean all $MAKE_OPT && \
    cd llvm_mode && make $MAKE_OPT

# Set up environment variables for ASAN
# We only enable ASAN during make (cmake gets stuck when testing system libraries)
env ASAN_OPTIONS='abort_on_error=1:symbolize=0:detect_leaks=0:detect_stack_use_after_return=1:detect_container_overflow=0:poison_array_cookie=0'

# Set up environment variables for StateAFL
ENV AFL_PATH=${STATEAFL}
ENV PATH=${STATEAFL}:${PATH}

RUN cd $WORKDIR && \
    git clone https://github.com/DCMTK/dcmtk dcmtk-stateafl && \
    cd dcmtk-stateafl && \
    git checkout 7f8564c && \
    patch -p1 < $WORKDIR/fuzzing.patch && \
    mkdir build && cd build && \
    cmake .. && \
    AFL_USE_ASAN=1 make dcmqrscp $MAKE_OPT


COPY --chown=ubuntu:ubuntu run-stateafl.sh ${WORKDIR}/run-stateafl

RUN cd $WORKDIR/dcmtk-stateafl/build/bin && \
    mkdir ACME_STORE && \
    cp $WORKDIR/dcmqrscp.cfg ./

