FROM tinydtls

# Import environment variable to pass as parameter to make (e.g., to make parallel builds with -j)
ARG MAKE_OPT

# Set up StateAFL
ENV STATEAFL="/home/ubuntu/stateafl"

RUN git clone https://github.com/stateafl/stateafl.git $STATEAFL && \
    cd $STATEAFL && \
    make clean all $MAKE_OPT && \
    cd llvm_mode && make $MAKE_OPT

# Set up environment variables for ASAN
env AFL_USE_ASAN=1
env ASAN_OPTIONS='abort_on_error=1:symbolize=0:detect_leaks=0:detect_stack_use_after_return=1:detect_container_overflow=0:poison_array_cookie=0:malloc_fill_byte=0:max_malloc_fill_size=16777216'

# Set up environment variables for StateAFL
ENV AFL_PATH=${STATEAFL}
ENV PATH=${STATEAFL}:${PATH}

# Dedicated instrumented version for StateAFL
RUN cd $WORKDIR && \
    git clone https://github.com/assist-project/tinydtls-fuzz.git tinydtls-stateafl && \
    cd tinydtls-stateafl && \
    git checkout 06995d4 && \
    cd tests && \
    CC=${STATEAFL}/afl-clang-fast make clean && \
    CC=${STATEAFL}/afl-clang-fast make ../libtinydtls.a $MAKE_OPT && \
    CC=${STATEAFL}/afl-clang-fast make $MAKE_OPT

COPY --chown=ubuntu:ubuntu run-stateafl.sh ${WORKDIR}/run-stateafl

